services:
  postgres:
    container_name: PostgreSQL
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=mydb

# Names our volume
volumes:
  postgres: